"""new

Revision ID: 127cce7164c1
Revises: cc9a46641606
Create Date: 2026-07-02 07:11:57.131108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127cce7164c1'
down_revision: Union[str, Sequence[str], None] = 'cc9a46641606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_history_task_id'), 'user_history', ['task_id'], unique=True)
    op.create_table('history_movie',
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['user_history.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie_base.id'], ),
    sa.PrimaryKeyConstraint('history_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_movie')
    op.drop_index(op.f('ix_user_history_task_id'), table_name='user_history')
    op.drop_table('user_history')
    # ### end Alembic commands ###
