"""image_id

Revision ID: 77730f0d8aa9
Revises: 127cce7164c1
Create Date: 2026-07-13 12:55:52.283913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77730f0d8aa9'
down_revision: Union[str, Sequence[str], None] = '127cce7164c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('image_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['image_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'image_id')
    # ### end Alembic commands ###
